WIP Border-radius and clip
Dedrakot/CSSBox pull request #2
Opened 2019-07-18 14:55 UTC by VladPush

2019-07-19 07:28 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/BlockBox.java
> +    protected RectangularShape applyClip(Shape current, RectangularShape newclip)
С учётом того, что shape-ы будут накладываться, мы не можем сказать, что у нас будет RectangularShape или ещё что-то. Вероятно придётся работать с Shape-ом.

2019-07-19 07:28 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +            int antialiasingAngleConstant = 4;
С названием не понятно, при чём здесь antialiasing? От того, что с ним дуги выглядят лучше, ни как не связывает его с количеством углов и border-radius-ом.

2019-07-19 07:32 UTC, Dedrakot commented
Не запутайся в методах получения областей. Лучше их разнести. Возможно, придётся допускать некоторое дублирование, наличие прямоугольной области для определения нечётких границ. Но при этом будет отдельный Shape, который будет получаться после clip-а. Тут смотри.

2019-07-19 07:38 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +            int antialiasingAngleConstant = 4;
Когда такие вещи беруться, требуется комментарий.

2019-07-19 07:38 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +                BorderRadiusSet antialiasingBorderRadius = new BorderRadiusSet(
Это дублирование кода тоже вызывает вопросы

2019-07-19 10:20 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +            int antialiasingAngleConstant = 4;
почему то вещи - Graphics2D.setRenderingHint()  связанные с качеством отрисовки/ размытием вообще не работают.
И я понял что это может решится другим способом( очень вероятно который будет  работать быстрей чем изменение свойств Graphics2D) - корректировкой положения border-radius.

2019-07-19 10:23 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +                BorderRadiusSet antialiasingBorderRadius = new BorderRadiusSet(
ой, а вот этого тут не должно быть вообще. я вынес это в отдельный метод.

2019-07-24 07:56 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/BackgroundImage.java
> +        if (clipped.width == 0) { // TODO УБРАТЬ ПОСЛЕ
Я честно не очень понимаю, почему ты не перенёс кодовую базу назад. Взял бы релиз, так искать придётся, где баг внесли. Делать баг репорт и предлагать исправление. Оно конечно неплохо, только таски у тебя будут другие.

2019-07-24 07:56 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/BlockBox.java
> +        Rectangle clippingRectangle = getAbsoluteBorderBounds();
У тебя здесь вопрос возник по поводу того, брать ли границу? Если это для собственной отрисовки, то брать (хоть для собственной может clip и не нужен). А для дочерних нужна внутренняя граница (т.е., там ещё и padding в минус). Пока не знаю, но название метода создаёт путаницу само по себе. Может в контексте и ясно станет, а так, куда и от чего мы этот clip добавляем, не понятно.

2019-07-24 07:56 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +            clipblock.addClip(g);
Вот это хотелось бы понять, а нам всегда нужно clip ставить? Тут ничего не нарушается. И зависимости выглядят странно, почему какой-то пришедший откуда-то clipBlock выставляется (почему он раньше, перед тем как нам начать рисовать этот элемент, не был выставлен?), а собственные ограничения игнорируются. Код тут не очень, поэтому и хотелось бы видеть логические связи между компонентами. Не код, просто порядок действий с описанием, чтобы видеть логику, которую мы хотим построить.

2019-07-24 07:56 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +            viewport.setVisibleRect(getAbsoluteBorderBounds());
Здесь тоже нужно пояснение. Почему мы так делаем, чего этим добиваемся. Выглядит вставкой не из той песни.

2019-07-24 07:56 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +            addClip(g);
Сразу вытекает ущёрбность реализации addClip. Ответственности у тебя чётко разделены. Есть случай, когда ты что-то делаешь c clipBlock, есть случай, когда со своими границами. Ты их мешаешь и это ни к чему хорошему не приведёт, как уже говорил, какая-то подтасовка с добавлением чего-то, если что-то не сработало.

2019-07-24 07:56 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
>          g.setColor(color); //restore original color
Такой момент, вот здесь значения востанавливаются, это уже дочерние элементы отрисованы? Это тоже хочется видеть на схеме, порядок, что мы сначало рисуем background-ы элементов одного уровня или спускаемся вниз на каждом элементе? Для этого выделялось время на исследование текущего рендеринга, чтобы ты мог сказать какие объекты, как и когда будут отрисованы. Чтобы можно было построить нормальную логическую схему. Которая уже может отличатся от текущей, причём достаточно сильно, но тут надо иметь общее представление. Ты должен знать, что и при каком clip-е мы рисуем, когда его восстанавливаем.

2019-07-24 07:56 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +            int antialiasingAngleConstant = 4;
Ух не скажи, примеры заполнения нашей фигуру, что у меня в test app-е попробуй без антиалайзинга отрисовать.
Дак что она эта величина делает? Она никак не зависит от значений, что мы передаём? А если там радиус 0 и нам рисовать дугу эллипса не надо, а ты угол меняешь?

2019-07-24 07:56 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/BackgroundImage.java
> +        if (clipped.width == 0) { // TODO УБРАТЬ ПОСЛЕ
Также, заведи практику не писать по-русски в кодовой базе. Потом тебе это прийдётся вычищать из истории коммитов.

2019-07-24 13:53 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +            addClip(g);
разделил

2019-07-24 13:53 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +            viewport.setVisibleRect(getAbsoluteBorderBounds());
да, оказалось не нужно.

2019-07-24 13:55 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +            clipblock.addClip(g);
согласен, игнорировать собственные ограничения нельзя. сейчас методы однозначно говорят сами за себя.

2019-07-24 14:10 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/BlockBox.java
> +        Rectangle clippingRectangle = getAbsoluteBorderBounds();
да, решение этого вроде как понятно.

2019-07-24 16:26 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/BlockBox.java
> +    protected RectangularShape applyClip(Shape current, RectangularShape newclip)
Далее, этот метод в покое оставить не вариант. Там есть списки, какие-то replaced элементы. На них на всех тоже надо нормальный clip применять. Этот метод будет некорректен.

2019-07-24 16:35 UTC, Dedrakot requested changes

2019-07-24 16:35 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/TextBox.java
> +            }
Немного не понял, что делает весь предшествующий кусок кода. Зачем со старым clip-ом что-то делать? Вроде addLayerBoundClip и так делает пересечение с текущим clip-ом

2019-07-25 11:55 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/TextBox.java
> +            }
да всё верно. оно туда никогда и не заходило.

2019-07-26 07:30 UTC, Dedrakot requested changes

2019-07-26 07:30 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
>              // TODO: this is an example only, all options not checked, for example, probalby oldPaint not required
У тебя это уже не пример. TODO был исключительно для тебя.

2019-07-26 07:30 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
>                      g.fill(rect);
Здесь уже не надо проверять, что getBgcolor() != null

2019-07-26 07:30 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +    private static final double ANTI_ALIASING_ANGLE_ADDING = 6.0;
Ещё раз могу сказать, сглаживание тут ни при чём. Называй переменную нормально (у тебя есть gap, border, corner или angle ANTI_ALIASING, да ADDING тоже кривоват, лучше убрать). Также, мне не понятно, почему ты его увеличиваешь радиусы, почему делаешь это не пропорционально радиусам элипса и т.д. Это пахнет тем, что работать не будет. Достаточно увеличить масштаб, поменять углы и всё поплывёт.  Приведи свои доводы, что это не так. Следующий большой минус сего дела. Тут, возможно, калибровать надо было shape, раз уж он так косо получается.

2019-07-26 07:30 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +            g.setStroke(new CSSStroke(border.top, bst, false));
Да, CSSStroke содержит стили, но то, что он тебе подходит надо ещё обосновать. Для этого нужна нормальная модель того, куда ты планируешь отрисовать. С позициями, паддингами и границей.

2019-07-26 07:30 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +                            TexturePaint paint = new TexturePaint(bimg, rect.getBounds2D());
лучше не пересоздавай Rectangle, возьми тот, что из  getAbsoluteBackgroundBounds(). Также, если рисуем границу , то может стоит не углы менять, а расширить область заливки.

2019-07-26 07:30 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +                    absbounds.y + emargin.top + border.top / 2,
Ты ошибочно берёшь разные значения border-а. У тебя он будет с одинаковой толщиной отрисован.

2019-07-26 07:32 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
>              // TODO: this is an example only, all options not checked, for example, probalby oldPaint not required
сделано.

2019-07-26 07:35 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
>                      g.fill(rect);
поправил.

2019-07-26 08:24 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +                            TexturePaint paint = new TexturePaint(bimg, rect.getBounds2D());
поправил.

2019-07-26 09:36 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +    private static final double ANTI_ALIASING_ANGLE_ADDING = 6.0;
как можно видеть из примеров ошибка эта неизменна на разном масштабе(от угла в 25 px до 2500 px - я думаю вся область реального применения захвачена). Я думаю это проблема пикселов - его либо есть либо нет.
![border0](https://user-images.githubusercontent.com/30935514/61942140-7d66df00-afa1-11e9-8698-367d7221788d.png)
![border6](https://user-images.githubusercontent.com/30935514/61942141-7d66df00-afa1-11e9-935e-9d80d3da4b4c.png)

2019-07-26 09:53 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +                    absbounds.y + emargin.top + border.top / 2,
не понял где я беру ошибочные значения. да он будет с одинаковой толщиной. чтобы он был с разной нам надо резать нашу фигуру на 4 кривые...

2019-07-26 09:55 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +            g.setStroke(new CSSStroke(border.top, bst, false));
эмм, мы тут рисуем Border, так и было до этого, разве в этой части что то должно поменяться?

2019-07-26 13:46 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/BlockBox.java
> +    protected RectangularShape applyClip(Shape current, RectangularShape newclip)
?

2019-07-26 13:51 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +    private static final double ANTI_ALIASING_ANGLE_ADDING = 6.0;
Да, например, с тем как ты сдвиг по границе берёшь на половину толщины. Которая будет варьироваться по модулю 2.

2019-07-26 13:53 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +    private static final double ANTI_ALIASING_ANGLE_ADDING = 6.0;
Они там, вроде для этих целей в CSSStroke параметр заводили, reverse. Тут тоже можешь ошибку набирать. Я имплементацию не смотрел, но логично, если параметр этой цели служит.

2019-07-26 13:55 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +            g.setStroke(new CSSStroke(border.top, bst, false));
Ну, было не так. Это кастомнй штрих и он был расчитан на то, что его с разных сторон фигуры будут по разному рисовать, надо по коду смотреть. А ты его по границе всей фигуры ведёшь, вполне можешь ошибку набирать.

2019-07-26 13:58 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +                    absbounds.y + emargin.top + border.top / 2,
Влад, ты рисуешь линюю одной толщины по всей фигуре. В CSS можно задать отдельно для каждой стороны, в этом случае у тебя всё с гарантией поедет.

2019-07-26 14:01 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +                    absbounds.y + emargin.top + border.top / 2,
Да, попробуй убрать из x и y половинную толщину border-а или прибавь целую. Да, вероятно ты проверял, но на всякий случай. Если не поможет, то вероятно дело в том, как задаётся штрих.

2019-07-26 14:03 UTC, Dedrakot commented
Эх, кончай издеваться force push-ем. Мы потом squash сделаем, а сейчас мне бы не помешал удобный способ смотреть только на то, что в последний коммит вошло.

2019-07-31 10:34 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +                    absbounds.y + emargin.top + border.top / 2,
не не помогло, именно прибавление половинной толщины бордера выставляет его по сторонам правильно, а вот углы остаются со щелями.

2019-07-31 11:04 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +            g.setStroke(new CSSStroke(border.top, bst, false));
а, моя ошибка, не учел... тут нам явно можно использовать простой Stroke

2019-07-31 11:11 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +    private static final double ANTI_ALIASING_ANGLE_ADDING = 6.0;
да, верно эта ошибка изменяется от толщины border.

2019-08-08 16:22 UTC, Dedrakot requested changes

2019-08-08 16:22 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/BlockBox.java
> +        if (Overflow.HIDDEN.equals(getOverflowX()) || Overflow.HIDDEN.equals(getOverflowY())) {
Как это зависти от overflow?

2019-08-08 16:22 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/BlockBox.java
> +            g.clip(new ArcCorneredRectangle(getAbsoluteSingleSizeBorderBounds(), borderRadius));
Может стоит хранить ArcCorneredRectangle вместо borderRadius?

2019-08-08 16:22 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +     * (because with ArcCorneredRectangle we can use only one size border)
Не могу сказать, что от ArcCorneredRectangle особо станет яснее. Напиши, что сейчас border-radius поддерживает border одной толщины для всей фигуры, поэтому берётся border.top.

2019-08-08 16:22 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/BlockBox.java
> +            getViewport().getRenderer().renderElementSpecialBorder(this);
Да, видимо придётся вынести метод в Renderer-е, но как-то не много смысла в названии "Отрисовка специальной границы". С точки зрения абстракции целиком, это метод дорисовки после отрисовки дочерних элементов :).
postChildRendering. В общем там нужен будет java doc с объяснением того, зачем сделали так криво.
Можно просто всегда там границу рисовать, тогда можно будет просто назвать drawBorder. Но это может быть не всегда удобно, если используются какие-то вычисления из drawBackground.

2019-08-08 16:22 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +                drawBorderRadiusBorder(g, shape);
Зачем тебе два раза границу отрисовывать?

2019-08-09 06:33 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +                drawBorderRadiusBorder(g, shape);
Если стоит overflow у блока то border должен быть поверх дочерних элементов, если overflow у блока нет то border должен быть за дочерними элементами, я правильно сужу?

2019-08-09 06:36 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +                drawBorderRadiusBorder(g, shape);
чтобы не было такой ситуации - 
![image](https://user-images.githubusercontent.com/30935514/62759127-22e17e80-ba89-11e9-883f-4af27fad7f2b.png)

2019-08-09 06:50 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +     * (because with ArcCorneredRectangle we can use only one size border)
поправил.

2019-08-09 06:51 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/BlockBox.java
> +        if (Overflow.HIDDEN.equals(getOverflowX()) || Overflow.HIDDEN.equals(getOverflowY())) {
ответил в https://github.com/Dedrakot/CSSBox/pull/2#discussion_r312125665

2019-08-09 07:20 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/BlockBox.java
> +            getViewport().getRenderer().renderElementSpecialBorder(this);
добавил doc в renderElementBorder.

2019-08-09 08:55 UTC, VladPush commented on src/main/java/org/fit/cssbox/layout/BlockBox.java
> +            g.clip(new ArcCorneredRectangle(getAbsoluteSingleSizeBorderBounds(), borderRadius));
Попробовал, там не получается так сделать из-за того что absbounds при инициализации самого объекта не тот что нужен на этапе рисования, и в получается мы не можем сформировать getAbsoluteSingleSizeBorderBounds()...

2019-08-09 09:35 UTC, Dedrakot commented on src/main/java/org/fit/cssbox/layout/ElementBox.java
> +                drawBorderRadiusBorder(g, shape);
Ну, мне в качестве ответа хватило бы ссылки либо на стандарт, либо на поведение хрома

2019-08-09 10:06 UTC, merged